//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecom_BOL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class offer
    {
        public int of_id { get; set; }
        public string product_name { get; set; }
        public string product_description { get; set; }
        public string image_path { get; set; }
        public Nullable<decimal> price { get; set; }
    }
}
