//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecom_BOL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_product_detaills_tbl
    {
        public int opd_id { get; set; }
        public Nullable<decimal> qty { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<int> p_id { get; set; }
        public Nullable<int> order_no { get; set; }
        public Nullable<int> o_addrs_id { get; set; }
    
        public virtual order_address_details_tbl order_address_details_tbl { get; set; }
        public virtual order_amount_details_tbl order_amount_details_tbl { get; set; }
        public virtual product_tbl product_tbl { get; set; }
    }
}
