//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecom_BOL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_address_details_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order_address_details_tbl()
        {
            this.order_product_detaills_tbl = new HashSet<order_product_detaills_tbl>();
        }
    
        public int o_addrs_id { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        public string zip_or_postal_code { get; set; }
        public string order_person_name { get; set; }
        public string contact_no { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_product_detaills_tbl> order_product_detaills_tbl { get; set; }
    }
}
