//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecom_BOL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_amount_details_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order_amount_details_tbl()
        {
            this.order_product_detaills_tbl = new HashSet<order_product_detaills_tbl>();
        }
    
        public int order_no { get; set; }
        public string order_date_and_time { get; set; }
        public Nullable<decimal> net_total { get; set; }
        public string order_status { get; set; }
        public string payment_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_product_detaills_tbl> order_product_detaills_tbl { get; set; }
    }
}
