//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecom_BOL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product_tbl()
        {
            this.order_product_detaills_tbl = new HashSet<order_product_detaills_tbl>();
            this.product_img = new HashSet<product_img>();
        }
    
        public int p_id { get; set; }
        public string product_name { get; set; }
        public string product_description { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> discount_percentage { get; set; }
        public Nullable<decimal> discounted_price { get; set; }
        public Nullable<decimal> net_price { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> sub_category_id { get; set; }
        public string brand_manfacturer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_product_detaills_tbl> order_product_detaills_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_img> product_img { get; set; }
        public virtual sub_category_tbl sub_category_tbl { get; set; }
    }
}
