//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecom_BOL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_img_tbl
    {
        public int user_img_id { get; set; }
        public string image_path { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual user_tbl user_tbl { get; set; }
    }
}
